### ISSUE TITLE
Update authentication to firebase authentication

### ISSUE THREAD

**Issue by tstegen** [jeangb/cadaver-back#3]
Migrer la configuration de spring securité en component

``` java
// https://docs.spring.io/spring-security/reference/servlet/oauth2/resource-server/jwt.html
@Bean
public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
	http.authorizeHttpRequests(authorizeRequests -> authorizeRequests.anyRequest().authenticated())
		.oauth2ResourceServer((oauth2) -> oauth2.jwt(Customizer.withDefaults()))
		.sessionManagement(sessionManagementConfigurer -> sessionManagementConfigurer.sessionCreationPolicy(SessionCreationPolicy.STATELESS));

	return http.build();
}
```

Spring properties
``` yml
spring:
    application:
        name: api
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
                    issuer-uri: https://securetoken.google.com/${project_id}
```

Link to create your firebase account for your project: 
https://medium.com/comsystoreply/authentication-with-firebase-auth-and-spring-security-fcb2c1dc96d
